Repository witseie-elen4010/2022-group-lab-004, pull requests merged in 2022-06, with the labels that each got.

#81 Player can return to lobby/singleplayer game
  Public/Script/multiPlayer.js
  Public/Script/result.js
  Public/Script/resultMulti.js
  Views/result.html
  Views/resultMulti.html
  index.js
Labels: review

#84 minor features added with sign in functionality
  Backend/WordleaccountManagement.js
  Backend/Wordleaccountprocess.js
  Routes/homeRoute.js
  Routes/lobbyRoute.js
  Routes/loginRoute.js
  Routes/modeRoute.js
  Views/home.html
  index.js
Labels: enhancement

#83 User can play multiplayer with 2 other players
  Public/CSS/multiPlayerStyle.css
  Public/Script/multiPlayer.js
  Views/multiPlayer.html
  index.js
Labels: developer story

#85 Sphumi
  Public/CSS/chooseWord.css
  Public/Script/chooseWord.js
  Public/Script/modeoptions.js
  Public/Script/multiPlayer.js
  Routes/chooseWordRoute.js
  Views/chooseWord.html
  index.js
  options.json
Labels: developer story
