Repository witseie-elen4010/2022-group-lab-004, pull requests merged in 2022-05, with the labels that each got.

#57 added on-screen keyboard
  Public/CSS/Keyboard.css
  Public/CSS/singleplayerstyle.css
  Public/Script/singleplayer.js
  Views/singleplayer.html
Labels: review

#58 Few changes made
  Public/CSS/Keyboard.css
  Public/Script/singleplayer.js
Labels: bug

#61 added calculate score
  Public/Script/singleplayer.js
Labels: developer story

#60 Added Functionalities handling Guesses and Evaluating Guesses on the server.
  Public/CSS/singleplayerstyle.css
  Public/Script/homepage.js
  Public/Script/modeoptions.js
  Public/Script/singleplayer.js
  Routes/homeRoute.js
  Routes/modeRoute.js
  Tests/gameplay.spec.js
  WordList.js
  index.js
  package-lock.json
  package.json
Labels: developer story

#65 Adding Colour
  Public/CSS/Keyboard.css
  Public/CSS/singleplayerstyle.css
  Public/Script/singleplayer.js
  package-lock.json
Labels: developer story

#66 User Can Create an Account
  Backend/WordleaccountManagement.js
  Backend/Wordleaccountprocess.js
  Backend/database/databaseTables.sql
  Backend/database_Connection.js
  Public/CSS/registerAnderror.css
  Public/Script/homepage.js
  Routes/homeRoute.js
  Routes/signUpRoute.js
  Tests/Accountprocess.spec.js
  Tests/gameplay.spec.js
  Views/Error.ejs
  Views/Register.html
  index.js
  package-lock.json
  package.json
Labels: developer story

#67 Created sign in functionality
  Backend/WordleaccountManagement.js
  Public/CSS/login.css
  Routes/loginRoute.js
  Views/Register.html
  Views/login.html
  index.js
Labels: developer story

#69 See Opponent's Board
  Public/CSS/multiPlayerStyle.css
  Public/Script/multiPlayer.js
  Views/multiPlayer.html
  index.js
Labels: developer story

#68 User is able to see their score after the game is completed.
  Backend/score.js
  Public/Script/modeoptions.js
  Public/Script/result.js
  Public/Script/singleplayer.js
  Tests/score.test.js
  Views/result.html
  WordList.js
  index.js
Labels: review

#72 Sign out functionality and session cookies implemented
  Backend/WordleaccountManagement.js
  Backend/Wordleaccountprocess.js
  Public/CSS/singleplayerstyle.css
  Views/login.html
  Views/singleplayer.html
  index.js
  package-lock.json
  package.json
Labels: developer story

#75 Host Generates unique game ID
  Public/Script/lobby.js
  Public/Script/modeoptions.js
  Routes/lobbyRoute.js
  Views/hostlobby.html
  Views/multiPlayer.html
  index.js
  package-lock.json
  package.json
  utils.js
Labels: developer story

#77 User Sees The Progression Of The Opponent
  Public/CSS/multiPlayerStyle.css
  Public/Script/modeoptions.js
  Public/Script/multiPlayer.js
  Views/multiPlayer.html
  index.js
Labels: developer story, review
